version: 2

build:
  os: ubuntu-22.04
  tools: {python: "3.10"}
  jobs:
    post_create_environment:
      - pip install -U furo breathe
    post_install:
      - apt install doxygen graphviz -y
      - cd docs && doxygen Doxyfile

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
