version: 2

build:
  os: ubuntu-22.04
  tools: {python: "3.10"}
  jobs:
    post_create_environment:
      - pip install -U furo breathe
    pre_build:
        - cd docs && doxygen Doxyfile
  apt_packages:
      - doxygen
      - graphviz

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false
