services:
  susicam-base:
    build:
      context: .
      dockerfile: base.Dockerfile
    image: susicam-base
    environment:
      - PATH_E130_Projekte=/dkfz/E130-Projekte
    volumes:
      - $PATH_E130_Projekte:/dkfz/E130-Projekte-ro:ro  # We don't want to accidentally manipulate any files on the network drive
  susicam:
    build: .
    depends_on:
      - susicam-base
    image: susicam
    container_name: susicam
    network_mode: host  # e.g. for Jupyter Lab
    shm_size: 10gb
    environment:
      - PATH_E130_Projekte=/dkfz/E130-Projekte
    volumes:
      - $PATH_E130_Projekte:/dkfz/E130-Projekte-ro:ro  # We don't want to accidentally manipulate any files on the network drive
      - /var/run/docker.sock:/var/run/docker.sock  # This allows Docker containers to be start from inside the container, but as siblings and not nested (https://stackoverflow.com/a/33003273/2762258)
    # Required to get copy-on-write to work: https://github.com/moby/moby/issues/18191#issuecomment-159280820
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
