name: Build, Test & Install

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-22.04, ubuntu-24.04 ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout project
        uses: actions/checkout@v4.1.7
      - name: Install apt dependencies
        run: |
          sudo apt install xvfb libgl1-mesa-dev -y
          chmod +x install_dependencies.sh
          sudo ./install_dependencies.sh
      - name: Build project
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_INSTALL_PREFIX=/usr ..
          xvfb-run -a --server-args="-screen 0 1024x768x24" make all -j
      - name: Run tests
        run: |
          cd build
          CTEST_OUTPUT_ON_FAILURE=1 xvfb-run -a --server-args="-screen 0 1024x768x24" make test -j
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and install DEB package
        run: |
          cd build
          xvfb-run -a --server-args="-screen 0 1024x768x24" make package -j
          sudo apt install ./xilens*.deb
      - name: Upload DEB package artifact
        uses: actions/upload-artifact@v4
        with:
          name: xilens_deb-${{ matrix.os }}
          path: build/xilens*.deb
      - name: Install application
        run: |
          cd build
          sudo make install
  install_deb:
    needs: build
    strategy:
      matrix:
        os: [ ubuntu-22.04, ubuntu-24.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download DEB package
        uses: actions/download-artifact@v4
        with:
          name: xilens_deb-${{ matrix.os }}
      - name: Install DEB package
        run: |
          sudo apt install ./xilens*.deb
      - name: Install non-apt dependencies
        run: |
          wget --progress=bar:force:noscroll https://www.ximea.com/downloads/recent/XIMEA_Linux_SP.tgz
          tar xzf XIMEA_Linux_SP.tgz
          cd package
          sed -i '/^[^#]/ s/\(^.*udevadm control --reload.*$\)/#\ \1/' scripts/install_steps
          sudo ./install
          cd ..
          git clone https://github.com/Blosc/c-blosc2.git
          cd c-blosc2
          git checkout v2.15.0
          mkdir build
          cd build
          cmake -DCMAKE_INSTALL_PREFIX=/usr ..
          sudo make install -j
      - name: Check app installation
        run: |
          xilens --version
  documentation:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout project
        uses: actions/checkout@v4.1.7
      - name: Documentation
        run: |
          sudo apt install doxygen graphviz
          sudo pip3 install -U sphinx furo breathe
          cd docs
          doxygen Doxyfile
          make html
